[2023-03-12T13:12:00.953+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Dag_master.dag_1_completed_status scheduled__2023-03-12T13:11:00+00:00 [queued]>
[2023-03-12T13:12:00.963+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Dag_master.dag_1_completed_status scheduled__2023-03-12T13:11:00+00:00 [queued]>
[2023-03-12T13:12:00.963+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-12T13:12:00.963+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-12T13:12:00.964+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-12T13:12:00.979+0000] {taskinstance.py:1300} INFO - Executing <Task(ExternalTaskSensor): dag_1_completed_status> on 2023-03-12 13:11:00+00:00
[2023-03-12T13:12:00.988+0000] {standard_task_runner.py:55} INFO - Started process 460 to run task
[2023-03-12T13:12:00.990+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Dag_master', 'dag_1_completed_status', 'scheduled__2023-03-12T13:11:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/child_master_dag.py', '--cfg-path', '/tmp/tmpli5yhcni']
[2023-03-12T13:12:00.991+0000] {standard_task_runner.py:83} INFO - Job 20: Subtask dag_1_completed_status
[2023-03-12T13:12:01.046+0000] {task_command.py:388} INFO - Running <TaskInstance: Dag_master.dag_1_completed_status scheduled__2023-03-12T13:11:00+00:00 [running]> on host 85f2bfd08863
[2023-03-12T13:12:01.116+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Dag_master
AIRFLOW_CTX_TASK_ID=dag_1_completed_status
AIRFLOW_CTX_EXECUTION_DATE=2023-03-12T13:11:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-12T13:11:00+00:00
[2023-03-12T13:14:01.263+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 215, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 120.14669275900815 seconds exceeds the specified timeout of 120.
[2023-03-12T13:14:01.272+0000] {taskinstance.py:1323} INFO - Immediate failure requested. Marking task as FAILED. dag_id=Dag_master, task_id=dag_1_completed_status, execution_date=20230312T131100, start_date=20230312T131200, end_date=20230312T131401
[2023-03-12T13:14:01.288+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 20 for task dag_1_completed_status (Sensor has timed out; run duration of 120.14669275900815 seconds exceeds the specified timeout of 120.; 460)
[2023-03-12T13:14:01.336+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-12T13:14:01.355+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
